// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfC0EgRqJo8fAM4xY7VexEHezVBtQt9YM',
    appId: '1:288535839111:web:e19c8cf707ad8c03b51322',
    messagingSenderId: '288535839111',
    projectId: 'fir-test-1ed02',
    authDomain: 'fir-test-1ed02.firebaseapp.com',
    storageBucket: 'fir-test-1ed02.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCznALfOMJyOFFvpjtXTJxC9X8v0k2o750',
    appId: '1:288535839111:android:a2234446321171b6b51322',
    messagingSenderId: '288535839111',
    projectId: 'fir-test-1ed02',
    storageBucket: 'fir-test-1ed02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcfluv3mY6E5fNYKmZJNzmtv_XsCEv664',
    appId: '1:288535839111:ios:df581c17bde9d16ab51322',
    messagingSenderId: '288535839111',
    projectId: 'fir-test-1ed02',
    storageBucket: 'fir-test-1ed02.appspot.com',
    iosClientId: '288535839111-4h6up06tjek7caup4npsd482ei4vks8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecosoftvmsvisitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcfluv3mY6E5fNYKmZJNzmtv_XsCEv664',
    appId: '1:288535839111:ios:8e9d4f317f4d29b8b51322',
    messagingSenderId: '288535839111',
    projectId: 'fir-test-1ed02',
    storageBucket: 'fir-test-1ed02.appspot.com',
    iosClientId: '288535839111-chdv5n3rcboqe112mvch3egv998qbr35.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecosoftvmsvisitor.RunnerTests',
  );
}
